# -*- coding: utf-8 -*-
"""assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sUXSqu-dh4Wp6VxJlgbuY_D7KU02mgcp
"""

import matplotlib.pyplot as plt
import numpy as np

def plot_line_graph(x, y, xlabel, ylabel, title):
    plt.figure(figsize=(8,5))
    plt.plot(x, y, marker='o', linestyle='-', color='b')
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)
    plt.grid(True)
    plt.show()

# 1. Living Room Lighting Distribution
corners = ["Corner 1", "Corner 2", "Corner 3", "Corner 4"]
lumens = [800, 1000, 700, 1200]
plot_line_graph(corners, lumens, "Fixture Position", "Brightness (Lumens)", "Living Room Lighting Distribution")

# 2. Wall Color Impact on Room Temperature
time = ["8 a.m.", "12 p.m.", "4 p.m.", "8 p.m."]
temp_white = [22, 26, 24, 20]
temp_grey = [24, 29, 27, 23]
temp_green = [23, 27, 25, 21]
plt.plot(time, temp_white, marker='o', label='White Wall')
plt.plot(time, temp_grey, marker='s', label='Dark Grey Wall')
plt.plot(time, temp_green, marker='^', label='Green Wall')
plt.xlabel("Time")
plt.ylabel("Temperature (°C)")
plt.title("Wall Color Impact on Room Temperature")
plt.legend()
plt.grid(True)
plt.show()

# 3. Acoustic Panel Thickness vs Noise Reduction
thickness = [1, 2, 3, 4, 5]
noise_reduction = [5, 10, 14, 18, 22]
plot_line_graph(thickness, noise_reduction, "Panel Thickness (cm)", "Noise Reduction (dB)", "Acoustic Panel Thickness vs Noise Reduction")

# 4. Natural Light Intensity Across the Day
time_hours = [6, 8, 10, 12, 14, 16, 18]
light_intensity = [150, 300, 600, 900, 700, 400, 200]
plot_line_graph(time_hours, light_intensity, "Time (Hours)", "Light Intensity (Lux)", "Natural Light Intensity Across the Day")

# 5. Energy Consumption of Light Bulbs
bulb_types = ["LED", "CFL", "Incandescent"]
energy_consumption = [10, 14, 60]
plot_line_graph(bulb_types, energy_consumption, "Bulb Type", "Energy Consumption (Watts)", "Energy Consumption of Light Bulbs")

# 6. Number of Shelves vs Storage Capacity
shelves = [2, 3, 4, 5]
storage_capacity = [10, 15, 20, 25]
plot_line_graph(shelves, storage_capacity, "Number of Shelves", "Storage Capacity (Cubic Feet)", "Number of Shelves vs Storage Capacity")

# 7. Distance of Light Fixture vs Brightness
distances = [1, 2, 3, 4, 5]
brightness = [400, 200, 100, 50, 25]
plot_line_graph(distances, brightness, "Distance from Light Source (m)", "Brightness (Lux)", "Distance of Light Fixture vs Brightness")

# 8. Paint Finish vs Cleaning Time
paint_finish = ["Matte", "Satin", "Glossy"]
cleaning_time = [10, 7, 5]
plot_line_graph(paint_finish, cleaning_time, "Paint Finish", "Cleaning Time (Minutes)", "Paint Finish vs Cleaning Time")

# 9. Furniture Weight Capacity vs Material
materials = ["Wood", "Steel", "Plastic"]
weight_capacity = [100, 150, 80]
plot_line_graph(materials, weight_capacity, "Material", "Weight Capacity (kg)", "Furniture Weight Capacity vs Material")

# 10. Natural Ventilation Efficiency
window_sizes = [2, 4, 6, 8]
airflow_rates = [50, 100, 150, 200]
plot_line_graph(window_sizes, airflow_rates, "Window Size (sq ft)", "Airflow Rate (m³/h)", "Natural Ventilation Efficiency")

# 11. Ceiling Height vs Room Temperature
ceiling_heights = [8, 10, 12, 14]
room_temperature = [28, 26, 24, 22]
plot_line_graph(ceiling_heights, room_temperature, "Ceiling Height (ft)", "Room Temperature (°C)", "Ceiling Height vs Room Temperature")

# 12. Flooring Material vs Walking Sound
flooring_materials = ["Wood", "Carpet", "Tile"]
noise_levels = [50, 30, 60]
plot_line_graph(flooring_materials, noise_levels, "Material", "Noise Level (dB)", "Flooring Material vs Walking Sound")

# 13. Curtain Thickness vs Sunlight Blocking
curtain_thickness = [1, 2, 3, 4, 5]
sunlight_blocking = [20, 40, 60, 80, 95]
plot_line_graph(curtain_thickness, sunlight_blocking, "Curtain Thickness (mm)", "Light Blocking (%)", "Curtain Thickness vs Sunlight Blocking")

# 14. Furniture Cost vs Quality
furniture_cost = [200, 400, 600, 800]
quality_rating = [6, 7, 8, 9]
plot_line_graph(furniture_cost, quality_rating, "Price (£)", "Quality Rating (/10)", "Furniture Cost vs Quality")

# 15. Number of Light Bulbs vs Electricity Bill
num_bulbs = [2, 4, 6, 8]
electricity_bill = [10, 20, 30, 40]
plot_line_graph(num_bulbs, electricity_bill, "Number of Light Bulbs", "Monthly Electricity Bill (£)", "Number of Light Bulbs vs Electricity Bill")